# Datastructures

## 🧱 Built-in Python Data Structures

| Structure | Description                         | Mutable | Example                                | Common Use Cases                        |
|-----------|-------------------------------------|---------|----------------------------------------|-----------------------------------------|
| List      | Ordered, dynamic array of items     | ✅      | `fruits = ['apple', 'banana', 'cherry']` | Collections, stacks, queues             |
| Tuple     | Ordered, immutable sequence         | ❌      | `point = (2, 3)`                        | Fixed data, function returns            |
| Set       | Unordered collection of unique elements | ✅   | `unique_numbers = {1, 2, 3}`            | Fast membership test, removing dupes    |
| Dict      | Key-value pairs (hash map)          | ✅      | `person = {'name': 'Alice', 'age': 30}` | Fast lookup, config/settings storage    |
| String    | Immutable text sequences            | ❌      | `greeting = "Hello"`                   | Text processing, data parsing           |


### 🔁 Mutable Types
You can change the content without changing the object’s identity (`id()`):

**Common mutable types:**
- `list`
- `dict`
- `set`
- `bytearray`

---

### 🔒 Immutable Types
You can’t change them directly — any modification creates a new object:

**Common immutable types:**
- `int`
- `float`
- `str`
- `tuple`
- `frozenset`
- `bytes`


In [2]:
x = "hello"
x += " world"
print(x)  # 'hello world'


hello world


In [3]:
x = "hello"
print(id(x)) 

x += " world"  # This creates a NEW string
print(x)       # 'hello world'
print(id(x))  


2709313973872
hello world
2709334855600


# 1. List

In [8]:
empty_list = []
my_list = [1, 2, 3, 4]
matrix = [[1, 2], [3, 4]]
mixed = [1, "two", 3.0, [4, 5]]


In [3]:
# 1. Creation

my_list = [1, 2, 3]
empty = []
from_range = list(range(5))
print("Created:", my_list, empty, from_range)

Created: [1, 2, 3] [] [0, 1, 2, 3, 4]


In [4]:
# 2. Adding Elements

my_list.append(4)
print("After append:", my_list)

my_list.extend([5, 6])
print("After extend:", my_list)

my_list.insert(1, 99)
print("After insert:", my_list)

my_list += [7, 8]
print("After += :", my_list)

After append: [1, 2, 3, 4]
After extend: [1, 2, 3, 4, 5, 6]
After insert: [1, 99, 2, 3, 4, 5, 6]
After += : [1, 99, 2, 3, 4, 5, 6, 7, 8]


In [5]:
# 3. Removing Elements

my_list.pop()  # removes last
print("After pop:", my_list)

my_list.pop(1)  # removes at index 1
print("After pop(1):", my_list)

my_list.remove(2)  # removes first occurrence of 2
print("After remove(2):", my_list)

After pop: [1, 99, 2, 3, 4, 5, 6, 7]
After pop(1): [1, 2, 3, 4, 5, 6, 7]
After remove(2): [1, 3, 4, 5, 6, 7]


In [8]:
# 4. Accessing Items
print("List ", my_list)
print("First item:", my_list[0])
print("Last item:", my_list[-1])
print("Slice [1:3]:", my_list[1:3])
print("Reversed:", my_list[::-1])

List  [1, 3, 4, 5, 6, 7]
First item: 1
Last item: 7
Slice [1:3]: [3, 4]
Reversed: [7, 6, 5, 4, 3, 1]


In [9]:
# 5. Updating Items

my_list[2] = 10
print("After update index 2:", my_list)

my_list[1:3] = [20, 30]
print("After slice update:", my_list)

After update index 2: [1, 3, 10, 5, 6, 7]
After slice update: [1, 20, 30, 5, 6, 7]


In [10]:
# 6. Searching / Checking

print("Is 3 in list?", 3 in my_list)
print("Index of 5:", my_list.index(5))
print("Count of 5:", my_list.count(5))

Is 3 in list? False
Index of 5: 3
Count of 5: 1


In [11]:
# 7. Sorting & Reversing

my_list.sort()
print("Sorted ascending:", my_list)

my_list.sort(reverse=True)
print("Sorted descending:", my_list)

print("Sorted (copy):", sorted(my_list))
my_list.reverse()
print("Reversed in-place:", my_list)

print("Reversed (copy):", list(reversed(my_list)))

Sorted ascending: [1, 5, 6, 7, 20, 30]
Sorted descending: [30, 20, 7, 6, 5, 1]
Sorted (copy): [1, 5, 6, 7, 20, 30]
Reversed in-place: [1, 5, 6, 7, 20, 30]
Reversed (copy): [30, 20, 7, 6, 5, 1]


In [12]:
# 8. List Comprehension

squares = [x**2 for x in range(5)]
print("Squares:", squares)

evens = [x for x in my_list if x % 2 == 0]
print("Even numbers:", evens)

Squares: [0, 1, 4, 9, 16]
Even numbers: [6, 20, 30]


In [13]:
# 9. Copying Lists
copy1 = my_list.copy()
copy2 = my_list[:]
print("Copy1:", copy1)
print("Copy2:", copy2)

Copy1: [1, 5, 6, 7, 20, 30]
Copy2: [1, 5, 6, 7, 20, 30]


In [14]:
# 10. Unpacking Lists

a, b, c = [1, 2, 3]
print("Unpacked:", a, b, c)

first, *rest = [10, 20, 30, 40]
print("First:", first, "Rest:", rest)

Unpacked: 1 2 3
First: 10 Rest: [20, 30, 40]


#### Python lists are dynamic. 🎯
    
    That means:

- You don’t need to declare a fixed size when creating a list.

- They automatically grow or shrink as you add or remove elements.

In [10]:
my_list = [1, 2, 3]
print(id(my_list))
my_list.append(4)          # ➜ [1, 2, 3, 4]
print(id(my_list))
my_list.extend([5, 6])     # ➜ [1, 2, 3, 4, 5, 6]
my_list.pop()              # ➜ [1, 2, 3, 4, 5]

2709335362624
2709335362624
2709335362624


In [27]:
import sys

lst = []
for i in range(10):
    lst.append(i)
    print(f"Length: {len(lst)}, Size in bytes: {sys.getsizeof(lst)}")


Length: 1, Size in bytes: 88
Length: 2, Size in bytes: 88
Length: 3, Size in bytes: 88
Length: 4, Size in bytes: 88
Length: 5, Size in bytes: 120
Length: 6, Size in bytes: 120
Length: 7, Size in bytes: 120
Length: 8, Size in bytes: 120
Length: 9, Size in bytes: 184
Length: 10, Size in bytes: 184


## Ndarry

A numpy.ndarray (n-dimensional array) is a homogeneous, multi-dimensional array — meaning all elements are of the same data type, and it's optimized for speed and efficiency.

| Feature              | Description                                                                 |
|----------------------|-----------------------------------------------------------------------------|
| Homogeneous data     | All elements have the same type (e.g. int32, float64)                       |
| Fixed size           | Once created, the shape doesn’t change (unlike lists)                      |
| Vectorized operations| Apply operations to entire arrays without loops                             |
| Memory efficient     | More compact than Python lists                                              |
| Multi-dimensional    | Supports 1D, 2D, 3D... nD arrays (e.g. matrices, tensors)                    |


## ⚡ Why Use `ndarray` over Python `list`?

| Operation           | list (Python)     | ndarray (NumPy)   |
|---------------------|-------------------|-------------------|
| Element-wise math   | ❌ Needs loops     | ✅ Fast & easy     |
| Memory usage        | ❌ Higher          | ✅ Lower           |
| Speed               | ❌ Slower          | ✅ Much faster     |
| Broadcasting        | ❌ No              | ✅ Yes             |


###  Example: Multiply Each Element by 2

In [29]:
my_list = [1, 2, 3, 4, 5]
doubled = [x * 2 for x in my_list]

print(doubled)  # Output: [2, 4, 6, 8, 10]


import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
doubled = my_array * 2

print(doubled)  # Output: [ 2  4  6  8 10]


[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


### Matrix Mutiplication

In [33]:
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
# Manual multiplication
print(A)
print(B)
result = [[A[0][0]*B[0][0] + A[0][1]*B[1][0], A[0][0]*B[0][1] + A[0][1]*B[1][1]],
          [A[1][0]*B[0][0] + A[1][1]*B[1][0], A[1][0]*B[0][1] + A[1][1]*B[1][1]]]
print(result)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[19, 22], [43, 50]]


In [34]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A)
print(B)
result = np.dot(A, B)
print(result)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


### Conditional Logic (np.where)

# Dictionary

In [15]:
# Dictionary Creation
my_dict = {"name": "Alice", "age": 25, "city": "New York"}
empty_dict = {}
print("Dictionary:", my_dict)


Dictionary: {'name': 'Alice', 'age': 25, 'city': 'New York'}


In [16]:
# Adding / Updating Items
my_dict["email"] = "alice@example.com"  # add
my_dict["age"] = 26                     # update
print("Updated dict:", my_dict)


Updated dict: {'name': 'Alice', 'age': 26, 'city': 'New York', 'email': 'alice@example.com'}


In [17]:
# Removing Items

my_dict.pop("city")
print("After pop:", my_dict)

del my_dict["email"]
print("After del:", my_dict)

# my_dict.clear()
# print("After clear:", my_dict)


After pop: {'name': 'Alice', 'age': 26, 'email': 'alice@example.com'}
After del: {'name': 'Alice', 'age': 26}


In [20]:
# Accessing Items
print("Name:", my_dict["name"])
print("Using get():", my_dict.get("age", "Not found"))
print("Using get():", my_dict.get("email", "Not found"))

Name: Alice
Using get(): 26
Using get(): Not found


In [21]:
# loop
for key, value in my_dict.items():
    print(f"{key} -> {value}")


name -> Alice
age -> 26


In [22]:
users = {
    "user1": {"name": "Alice", "age": 25},
    "user2": {"name": "Bob", "age": 30},
    "user3": {"name": "Charlie", "age": 28},
    "user4": {"name": "Anna", "age": 22}
}


for uid, details in users.items():
    if details["name"].startswith("A"):
        print(f"{uid} → {details['name']}")

        

user1 → Alice
user4 → Anna


In [24]:
flattened = {}
for outer_key, inner_dict in users.items():
    for inner_key, value in inner_dict.items():
        flattened[f"{outer_key}.{inner_key}"] = value

print(flattened)

{'user1.name': 'Alice', 'user1.age': 25, 'user2.name': 'Bob', 'user2.age': 30, 'user3.name': 'Charlie', 'user3.age': 28, 'user4.name': 'Anna', 'user4.age': 22}
